# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe0b4afc84c2d95474cafe90274445afa6d1f89b711d68a2a2d450f20e9f4f61135dba605c0014231ff32f0815393df6640c2fed7bfcd71c7f5fc49a70efb1ed

test:
  secret_key_base: 16dc4d7026dc47d16dfa0e933ba56b0c54f531fa277aa6f3eff72320df65e9b75d79dd48d2d22cb977717f19e8f544a48f5564203b290692b50fea407906a316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
